# Generated by Django 5.0.4 on 2024-05-13 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_url_alter_post_last_viewed_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_viewed_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 16, 21, 30, 491817)),
        ),
    ]
